spring.application.name=fooddelivery

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/food_delivery
spring.datasource.username=mustafa
spring.datasource.password=ms5919
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate/JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=ZfBkT+RDqkNxssQ/s1Ch7CghQ0S9EEguX8L59NtK+Bg=
spring.security.user.name=admin
spring.security.user.password=admin